### ISSUE TITLE
Auto-linking broken:

### ISSUE THREAD

**Issue by dlr-cjs** [FEAT-ML/scengen#59]
# Summary
If multiple agents are created and to be linked to each other, auto-linking does not work.

# Steps to reproduce
config.yaml
``` YAML 
create:
  - type_template: ./templates/DemandTrader.yaml
    count: 2
    this_agent: dynamicDemandTrader
    external_ids:
      exchange: dynamicExchange
    
  - type_template: ./templates/Exchange.yaml
    count: 2
    this_agent: dynamicExchange
```

DemandTrader.yaml:
``` YAML
Agent:
  Type: DemandTrader
  Attributes:
    Loads:
      - ValueOfLostLoad: 4000.0
        DemandSeries: 1

Contracts:
  - SenderId: //exchange
    ReceiverId: //THISAGENT
    ProductName: GateClosureInfo
    FirstDeliveryTime: -10
    DeliveryIntervalInSteps: 3600
```

Exchange.yaml
``` YAML
Agent:
  Type: DayAheadMarketSingleZone
  Attributes:
    Clearing:
      DistributionMethod: SAME_SHARES
    GateClosureInfoOffsetInSeconds: 11

Contracts: []
```

## Expected result:
Proper error message that explains why the linking could not be performed and how to fix it.

## Actual result:
Unclear error message: "Exception: Found replacement Identifier '//dynamicExchange' with no corresponding Agent in Contract "
